Update variable.py
Removed dom.name because it triggers the error *AttributeError: 'unicode' object has no attribute 'name'* when an operation is lauched